const fs = require('fs');
const path = require('path');

const generatedDir = path.join(__dirname, '../src/generated');

if (!fs.existsSync(generatedDir)) {
    console.error(`Generated directory not found: ${generatedDir}`);
    process.exit(1);
}

const files = fs.readdirSync(generatedDir);

const exportsContent = files
    .filter(file => file.endsWith('.ts') && file !== 'index.ts')
    .map(file => `export * from "./${file.replace('.ts', '.js')}";`)
    .sort()
    .join('\n');

const header = `// This file is automatically generated by scripts/generate-exports.cjs\n// Do not edit this file manually.\n\n`;

fs.writeFileSync(path.join(generatedDir, 'index.ts'), header + exportsContent + '\n');

console.log('Successfully generated gRPC exports in src/generated/index.ts');
