import { createGrpcTransport } from "@connectrpc/connect-node";
import { createClient } from "@connectrpc/connect";
import {
  JobHub,
  JobListenRequest,
  JobListenResponse,
  ExecuteJobMessage,
  JobResponse,
  JobStatus,
  JobStatus_State,
  JobResult,
  StepReport,
  Telemetry,
} from "uap-node";
import { Timestamp, Struct } from "@bufbuild/protobuf";
import { parseArgs } from "node:util";
import { TestLogger, TestRunner } from "@hsgamer/side-engine";
import { Builder, WebDriver } from "selenium-webdriver";
import { 
  WebDriverExecutor, 
  Variables, 
  PlaybackStates, 
  PlaybackState, 
  CommandStates, 
  CommandState 
} from "@seleniumhq/side-runtime";
import type { CommandShape, TestShape } from "@seleniumhq/side-model";

/**
 * Normalization types for the Selenium IDE (.side) report structure.
 * These types align with the internal reports generated by @hsgamer/side-engine.
 */
type PlaybackTimestamp = {
  state: PlaybackState;
  timestamp: Date;
};

type CommandTimestamp = {
  state: CommandState;
  timestamp: Date;
  message?: string;
  error?: Error;
};

type TestCommandReport = {
  id: string;
  command: CommandShape;
  state: CommandState;
  timestamp: CommandTimestamp[];
};

type TestReport = {
  id: string;
  name: string;
  state: PlaybackState;
  timestamp: PlaybackTimestamp[];
  commands: TestCommandReport[];
  logs: string[];
};

// --- Global State for Graceful Shutdown ---
const activeDrivers = new Set<WebDriver>();
let isShuttingDown = false;

// --- Command Line Argument Parsing ---
const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    name: { type: "string", short: "n" },
    url: { type: "string", short: "u" },
    selenium: { type: "string", short: "s" },
  },
});

const HUB_URL = values.url || process.env.HUB_URL || "http://localhost:9090";
const CLIENT_NAME = values.name || process.env.CLIENT_NAME || "SideAgent-" + Math.random().toString(36).substring(7);
const SELENIUM_REMOTE_URL = values.selenium || process.env.SELENIUM_REMOTE_URL;

console.log(`Starting UAP Node Side Agent: ${CLIENT_NAME}`);

// Initialize the ConnectRPC transport and client for the JobHub service.
const transport = createGrpcTransport({ baseUrl: HUB_URL, httpVersion: "2" });
const client = createClient(JobHub, transport);

/**
 * Main application loop. Establishes the control plane connection (Listen)
 * and maintains it with an exponential backoff strategy upon failure.
 */
async function main() {
  let delay = 1000;
  while (!isShuttingDown) {
    try {
      // Register with the Hub and announce 'selenium-side' capability.
      const listenRequest = new JobListenRequest({
        displayName: CLIENT_NAME,
        capabilities: [{ testType: "selenium-side" }],
      });

      console.log(`[Listen] Connecting to JobHub at ${HUB_URL}...`);
      for await (const directive of client.listen(listenRequest)) {
        if (isShuttingDown) break;
        delay = 1000; // Reset backoff on successful communication.

        if (directive.content.case === "runJob") {
          const sessionId = directive.content.value.sessionId;
          console.log(`[Listen] Received Job Assignment: ${sessionId}`);
          // Execute jobs concurrently without blocking the main listen loop.
          executeJob(sessionId).catch(console.error);
        }
      }
    } catch (err) {
      if (isShuttingDown) break;
      console.error(`[Listen] Connection error: ${err}. Retrying in ${delay}ms...`);
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay = Math.min(delay * 2, 60000);
    }
  }
}

/**
 * Manages a single bi-directional test execution session (Execute RPC).
 * Handles the session handshake and translates Hub instructions into engine actions.
 */
async function executeJob(sessionId: string) {
  const outboundQueue: ExecuteJobMessage[] = [];
  let resolveOutbound: (() => void) | null = null;

  /**
   * Utility to push a JobResponse update into the outbound stream.
   */
  function pushUpdate(response: JobResponse["response"]) {
    outboundQueue.push(new ExecuteJobMessage({
      content: { case: "update", value: new JobResponse({ timestamp: Timestamp.now(), response }) }
    }));
    if (resolveOutbound) { resolveOutbound(); resolveOutbound = null; }
  }

  /**
   * Async generator that yields messages from the outbound queue to the Hub.
   */
  async function* sendMessages(): AsyncGenerator<ExecuteJobMessage> {
    // 1. First message MUST be the session_id to correlate the stream on the Hub.
    yield new ExecuteJobMessage({ content: { case: "sessionId", value: sessionId } });
    
    while (!isShuttingDown) {
      if (outboundQueue.length > 0) yield outboundQueue.shift()!;
      else await new Promise<void>((r) => (resolveOutbound = r));
    }
  }

  try {
    const session = client.execute(sendMessages());
    console.log(`[Job ${sessionId}] Execution session established.`);

    for await (const instruction of session) {
      if (isShuttingDown) break;
      if (instruction.content.case === "jobInit") {
        // Initialization configuration received; start the Selenium engine.
        await runSideTest(sessionId, instruction.content.value.payload as any, instruction.content.value.runtimeEnv!, pushUpdate);
      } else if (instruction.content.case === "command") {
        // Inter-session command (e.g., STOP/PAUSE).
        console.log(`[Job ${sessionId}] Received command: ${instruction.content.case}`);
      }
    }
  } catch (err) {
    if (!isShuttingDown) {
      console.error(`[Job ${sessionId}] Session terminated:`, err);
    }
  }
}

/**
 * The core execution engine. Orchestrates the Selenium WebDriver and side-engine.
 * Maps engine lifecycle events (Starting, Logging, Completed) to UAP messages.
 */
async function runSideTest(
  sessionId: string,
  payload: any,
  runtimeEnv: Struct,
  pushUpdate: (res: JobResponse["response"]) => void
) {
  // 1. Protocol Validation
  if (payload.type !== "selenium-side") {
    pushUpdate({ case: "status", value: new JobStatus({ state: JobStatus_State.INVALID, message: "Type mismatch: expected selenium-side" }) });
    return;
  }

  // 2. Payload Parsing
  let sideCommands: CommandShape[];
  try {
    const rawContent = payload.content.case === "rawData" 
      ? new TextDecoder().decode(payload.content.value)
      : JSON.stringify(payload.content.value.toJson());
    sideCommands = JSON.parse(rawContent) as CommandShape[];
  } catch (e: any) {
    pushUpdate({ case: "status", value: new JobStatus({ state: JobStatus_State.INVALID, message: "JSON parsing failed" }) });
    return;
  }

  // 3. Environment Setup
  pushUpdate({ case: "status", value: new JobStatus({ state: JobStatus_State.ACKNOWLEDGED, message: "Initializing Selenium engine..." }) });

  const test: TestShape = { id: sessionId, name: "UAP Session Job", commands: sideCommands };
  const driverBuilder = new Builder();
  
  if (SELENIUM_REMOTE_URL) {
    driverBuilder.usingServer(SELENIUM_REMOTE_URL);
  }
  
  const browser = runtimeEnv.fields["selenium_browser"]?.kind.case === "stringValue" 
    ? runtimeEnv.fields["selenium_browser"].kind.value 
    : "chrome";
  driverBuilder.forBrowser(browser);
  
  const logger = new TestLogger();
  
  // Real-time log redirector: intercepts console logs and streams them as UAP Telemetry.
  const originalLog = console.log;
  console.log = (...args: any[]) => {
    originalLog(...args);
    pushUpdate({ case: "telemetry", value: new Telemetry({ message: args.join(" ") }) });
  };

  let driver: WebDriver | null = null;
  try {
    driver = await driverBuilder.build();
    activeDrivers.add(driver);

    const testRunner = TestRunner.createRunner(test, {
      logger: logger.createConsole(),
      variables: new Variables(),
      executor: new WebDriverExecutor({ driver }),
    });

    // 4. Test Execution
    pushUpdate({ case: "status", value: new JobStatus({ state: JobStatus_State.EXECUTING, message: "Running test steps..." }) });
    await testRunner.run();

    // 5. Results Mapping
    const report = (await testRunner.createReport(logger)) as TestReport;
    const finalState = report.state === PlaybackStates.FINISHED ? JobStatus_State.COMPLETED : JobStatus_State.FAILED;

    // Send final structured JobResult to the Hub.
    pushUpdate({
      case: "result",
      value: new JobResult({
        status: new JobStatus({ state: finalState }),
        steps: report.commands.map((cmd) => new StepReport({
          name: `${cmd.command.command} ${cmd.command.target}`,
          status: new JobStatus({ 
            state: cmd.state === CommandStates.PASSED ? JobStatus_State.COMPLETED : JobStatus_State.FAILED,
            message: cmd.timestamp.find(t => t.message)?.message
          }),
        })),
        logs: report.logs,
      }),
    });

    // Update global lifecycle status to termination state.
    pushUpdate({ case: "status", value: new JobStatus({ state: finalState }) });
  } catch (err: any) {
    if (!isShuttingDown) {
      pushUpdate({ case: "status", value: new JobStatus({ state: JobStatus_State.FAILED, message: `Execution Error: ${err.message}` }) });
    }
  } finally {
    if (driver) {
      activeDrivers.delete(driver);
      await driver.quit().catch(() => {});
    }
    // Restore original console log to prevent leaks.
    console.log = originalLog;
  }
}

/**
 * Graceful shutdown handler. Ensures all active WebDriver instances are quitted
 * and active streams are closed before the process exits.
 */
async function shutdown() {
  if (isShuttingDown) return;
  isShuttingDown = true;
  console.log("\n[Shutdown] Graceful shutdown initiated...");

  const quitPromises = Array.from(activeDrivers).map(async (driver) => {
    try {
      await driver.quit();
    } catch (err) {
      // Ignore errors during final cleanup
    }
  });

  await Promise.all(quitPromises);
  activeDrivers.clear();

  console.log("[Shutdown] Cleanup complete. Exiting.");
  process.exit(0);
}

// Register shutdown hooks for system signals.
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

// Entry point.
main().catch(console.error);
