import { CommandState, PlaybackState } from "@seleniumhq/side-runtime";
import type { CommandShape } from "@seleniumhq/side-model";

/**
 * Normalization types for the Selenium IDE (.side) report structure.
 * These types align with the internal reports generated by @hsgamer/side-engine.
 */
export type PlaybackTimestamp = {
  state: PlaybackState;
  timestamp: Date;
};

export type CommandTimestamp = {
  state: CommandState;
  timestamp: Date;
  message?: string;
  error?: Error;
};

export type TestCommandReport = {
  id: string;
  command: CommandShape;
  state: CommandState;
  timestamp: CommandTimestamp[];
};

export type TestReport = {
  id: string;
  name: string;
  state: PlaybackState;
  timestamp: PlaybackTimestamp[];
  commands: TestCommandReport[];
  logs: string[];
};
