/**
 * @file generate-index.js
 * Automatically generates the uap-node entry point (index.ts) based on
 * the modular components generated by 'buf generate'.
 */

import fs from 'fs';
import path from 'path';

const GENERATED_DIR = './src/generated';
const OUTPUT_FILE = './src/index.ts';

function generate() {
  console.log('[uap-node] Generating barrel file...');

  if (!fs.existsSync(GENERATED_DIR)) {
    console.error(`[uap-node] Error: Generated directory not found at ${GENERATED_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(GENERATED_DIR)
    .filter(file => file.endsWith('.ts'))
    .map(file => file.replace(/\.ts$/, ''))
    .sort();

  const exports = files.map(baseName => `export * from './generated/${baseName}.js';`);
  
  const content = [
    '// @generated by uap-node build workflow. Do not edit manually.',
    ...exports,
    ''
  ].join('\n');

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`[uap-node] Successfully exported ${files.length} components to ${OUTPUT_FILE}`);
}

generate();
