server:
  port: 8080
  host: 0.0.0.0

data:
  persistence-units:
    jakarta:
      - name: "testgenesis"
        connection:
          url: "jdbc:h2:file:./testgenesis_cms;DB_CLOSE_DELAY=-1"
          user: "sa"
          password: ""
          jdbc-driver-class-name: "org.h2.Driver"
        properties:
          jakarta.persistence.schema-generation.database.action: "create"
          eclipselink.ddl-generation: "create-tables"
          eclipselink.ddl-generation.output-mode: "database"
          eclipselink.deploy-on-startup: "true"
          eclipselink.weaving: "false"
          eclipselink.logging.level: "FINE"